#!/usr/bin/env python
"""
This script initilizes simple python node.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'
import rospy
from ros_services_examples.srv import *

def initlize_node():
    '''
    Initilize node and spin which simply keeps python 
    from exiting until this node is stopped
    '''
    rospy.init_node('simple_time_example_node', anonymous=False)
    rospy.loginfo("simple_time_example_node is now running")

    now1 = rospy.Time.now()
    rospy.loginfo("Current time (now1): %i %i", now1.secs, now1.nsecs)

    now2 = rospy.get_rostime()
    rospy.loginfo("Current time (now2): %i %i", now2.secs, now2.nsecs)

    rospy.sleep(10.)

    d = rospy.Duration(10.0)
    rospy.sleep(d)

    r = rospy.Rate(10) # 10hz
	while not rospy.is_shutdown():
		r.sleep()


    rospy.spin()

if __name__ == '__main__':
    initlize_node()