#!/usr/bin/env python
"""
This script demonstrates the way of requesting service.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'
import rospy
from ros_services_examples.srv import *

def initlize_node():
    '''
    Initilize node and spin which simply keeps python 
    from exiting until this node is stopped
    '''
    rospy.init_node('simple_client_python_example_node', anonymous=False)
    rospy.loginfo("simple_client_python_example_node is now running")

    rospy.wait_for_service('node_info_query')

    try:
        node_info_service = rospy.ServiceProxy('node_info_query', NodeInfoQuery)
        req = NodeInfoQueryRequest()
        req.node_name.data = "simple_client_python_example_node"
        resp = node_info_service(req)
        rospy.loginfo("Response recieved : %d",resp.node_id.data)
    except rospy.ServiceException, e:
        print "Service call failed: %s"%e

    rospy.spin()

if __name__ == '__main__':
    initlize_node()