#!/usr/bin/env python
"""
This script initilizes simple class based python node.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'
import rospy

class DemoClass():
    def __init__(self):
        self.initilize_parameters(0, 0.0)

    def initilize_parameters(self, number_count, total_sum):
        rospy.loginfo("Initlizing class variables.")
        self.number_count = number_count;
        self.total_sum = total_sum;

def initlize_node():
    '''
    Initilize node and spin which simply keeps python 
    from exiting until this node is stopped
    '''
    rospy.init_node('class_based_example1_node', anonymous=False)
    rospy.loginfo("class_based_example1_node is now running")
    demo_class = DemoClass()
    demo_class.initilize_parameters(10, 10.0)
    rospy.spin()

if __name__ == '__main__':
    initlize_node()