#!/usr/bin/env python
"""
This script initilizes simple python node.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'
import rospy
from custom_msg_example1.msg import NodeData 

def initlize_node():
    '''
    Initilize node and spin which simply keeps python 
    from exiting until this node is stopped
    '''
    rospy.init_node('custom_msg_python_simple_node', anonymous=False)
    rospy.loginfo("custom_msg_python_simple_node is now running")

    node_data = NodeData()
    node_data.vector_position.x = 0.01
    node_data.vector_position.y = 0.01
    node_data.vector_position.z = 0.01

    node_data.point_position.x = 0.1
    node_data.point_position.y = 0.2
    node_data.point_position.z = 0.01

    rospy.spin()

if __name__ == '__main__':
    initlize_node()