#!/usr/bin/env python
"""
This script is a simple python node which imports
source code of std_messages_examples.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'

import ros_python_std_messages_examples_ros.std_messages_examples

if __name__ == '__main__':
    ros_python_std_messages_examples_ros.std_messages_examples.main()