#!/usr/bin/env python
"""
This script initilizes simple python node.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'
import rospy
from ros_services_examples.srv import *

def initlize_node():
    '''
    Initilize node and spin which simply keeps python 
    from exiting until this node is stopped
    '''
    rospy.init_node('simple_service_example_node', anonymous=False)
    rospy.loginfo("simple_service_example_node is now running")

    rospy.wait_for_service('node_info_service')

    try:
	    node_info_service = rospy.ServiceProxy('node_info_service', NodeInfoQuery)
	    resp1 = node_info_service("simple_service_example_node")
    except rospy.ServiceException, e:
        print "Service call failed: %s"%e

    rospy.spin()

if __name__ == '__main__':
    initlize_node()