#!/usr/bin/env python
"""
This script is a simple python node which imports
source code of std_messages_examples.
"""
#-*- encoding: utf-8 -*-
__author__ = 'shehzad ahmed'

import rospy
from std_msgs.msg import String

if __name__ == '__main__':
    '''
    Initilize node and string type publish topic at the loop rate.
    '''
    rospy.init_node('simple_publisher_python_examples_node', anonymous=False)
    rospy.loginfo("simple_publisher_python_examples_node is now running")

    eventout_pub = rospy.Publisher("~event_out", String, queue_size=100)

    eventout_msg = String()
    eventout_msg.data = "start"

    loop_rate = rospy.Rate(10)
    while not rospy.is_shutdown():
    	eventout_pub.publish(eventout_msg)
    	loop_rate.sleep()